# BAB 1: VECTORE AND MATRICES

## 1.1 VECTORE

### 1.1.1 GEOMETRY WITH VECTORE

Skalar adalah bilangan real dengan hanya besaran. Panjang, massa, dan densitas adalah contoh besaran skalar. 

Vektor adalah kuantitas dengan besaran dan arah yang dapat direpresentasikan secara grafis sebagai panah, yaitu garis berarah dan secara aljabar sebagai pasangan/rangkap tiga $a= [a_x, a_y]^T/[a_x,a_y,a_z]^T$ dari dua/tiga bilangan riil dalam sistem koordinat Kartesius 2D/3D.

Vektor 3D $[a_x,a_y,a_z]^T$ memiliki arah dari titik asal [0, 0, 0] ke titik $[a_x,a_y,a_z]$ dan besar yang sama dengan panjang panah atau jarak dari titik asal ke titik tersebut, yaitu $ \| \mathbf{a} \| = \sqrt{a_x^2 + a_y^2 + a_z^2} $

Bentuk representasi vektor dalam sistem koordinat 3D menggunakan vektor satuan:
$$ a=[a_x,a_y,a_z]^T = \begin{bmatrix} a_x\\ a_y\\a_z \end{bmatrix} = a_xu_x+a_yu_y+a_zu_z \quad \text{(1.1.1)}$$

menunjukkan bahwa $ux, uy dan uz$ adalah vektor satuan sepanjang sumbu +x, +y, dan +z dalam ruang tiga dimensi, yaitu:
$$u_x = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}, \quad u_y = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}, \quad u_z = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix} \quad \text{(1.1.2)}$$

![Figure 1.1 Plots of a vector and the sum of two vectors](Screenshot%202025-07-07%20133623.png)

### 1.1.2 DOT PRODUCT

Produk titik (atau produk skalar, atau produk dalam) dari dua vektor $a=a_xu_x + a_yu_y + a_zu_z$ dan $b=b_xu_x+b_yu_y+b_zu_z$ didefinisikan sebagai:
$$ a \cdot b = |a| |b| \cos(\theta_{ab}) \quad \text{(1.1.3)}$$
dimana $\theta_{ab}$ adalah sudut antara kedua vektor tersebut. Persamaan kedua dapat dibuktikan menggunakan hukum distribusi untuk produk titik dan ortonormalitas antara vektor satuan $ux,uy,uz.$

Catatan:

* Bahwa magnitudo, yang disebut sebagai norma (norma Euclidean atau norma $l2$) dari sebuah vektor 𝑎 dapat ditemukan dari produk titik antara vektor 𝑎 dengan dirinya sendiri sebagai:
$$ ||\mathbf{a}||^2 = \mathbf{a} \cdot \mathbf{a} = a_x^2 + a_y^2 + a_z^2 \quad \text{(1.1.4)}$$

* Selain itu, dua vektor dikatakan ortogonal atau tegak lurus jika dan hanya jika produk titik mereka adalah nol:
$$\mathbf{a} \cdot \mathbf{b} =0 \quad \text{(1.1.5)}$$

#### 1.1.2.1 The Angle Between Two Nonzero Vectore

Untuk dua vektor non-zero 𝑎 dan 𝑏, sudut antara keduanya dapat ditemukan dengan menggunakan rumus produk titik:
$$ \cos(\theta) = \frac{a \cdot b}{\|a\| \|b\|} \quad \text{(1.1.6)}$$
Secara geometris, sudut 𝜃 adalah sudut yang dibentuk oleh ujung vektor 𝑎 dan 𝑏 jika keduanya diletakkan dengan pangkalnya di titik yang sama.


Untuk mendapatkan 𝜃, kita pakai definisi dari dot product (produk titik) dua vektor: 
$$\mathbf{a} \cdot \mathbf{b} = \|\mathbf{a}\| \|\mathbf{b}\| \cos(\theta)$$
Kita ubah rumus ini untuk mencari cos(𝜃):
$$\cos(\theta) = \frac{\mathbf{a} \cdot \mathbf{b}}{\|\mathbf{a}\| \|\mathbf{b}\|}$$
$$\theta = \cos^{-1} \left( \frac{\|\mathbf{a}\| \|\mathbf{b}\|}{\mathbf{a} \cdot \mathbf{b}} \right)$$

#### 1.1.2.2 The Law of Cosines (Cosine Formula or Cosine Rule) 

Hukum cosinus digunakan untuk menemukan hubungan antara panjang sisi-sisi segitiga dan sudut di antara sisi-sisi tersebut. Dalam konteks vektor, hukum ini bisa diturunkan dari dot product (perkalian titik) dua vektor.

* Kita dapat mempertimbangkan segitiga dengan tiga sisi yang direpresentasikan oleh vektor:
$$a = [ax, ay, az]ᵗ$$
$$b = [bx, by, bz]ᵗ$$
$$c = a - b = [ax - bx, ay - by, az - bz]ᵗ$$
* Panjang sisi c dapat dinyatakan sebagai:
$$||c||^2 = ||a||^2 + ||b||^2 - 2||a||||b|| \cos \theta$$

Tambahan:

Rumus ini diturunkan dengan menghitung $||c||^2$ menggunakan selisih koordinat:
$$||c||^2=(a_x - b_x)^2 + (a_y - b_y)^2 + (a_z - b_z)^2$$
Selanjutnya menerapkan sifat dot product:
$$||c||^2 = ||a||^2 + ||b||^2 - 2 (a \cdot b)$$
Sehingga, karena $a \cdot b = ||a||\, ||b|| \cos \theta$, maka:
$$||c||^2 = ||a||^2 + ||b||^2 - 2||a||||b|| \cos \theta \quad \text{(1.1.7)}$$ 

#### 1.1.2.3 Projections of Vector a onto Vectors b and $b^\perp$


Besarnya komponen vektor a sepanjang vektor b adalah $||a||cos\theta ab$ dan dapat ditemukan dari hasil perkalian titik (dot product) kedua vektor tersebut sebagai:
$$\operatorname{comp}_b a = \frac{a \cdot b}{||b||} \quad \text{(1.1.8)}$$
Kita dapat mengalikannya dengan vektor satuan ke arah b, yaitu, $b/|b|$ untuk menemukan proyeksi a pada b sebagai:
$$\operatorname{proj}_{\mathbf{b}} \, \mathbf{a} = \frac{(\mathbf{a} \cdot \mathbf{b})}{\|\mathbf{b}\|^2} \mathbf{b}\quad \text{(1.1.9)}$$
Kita dapat mengurangkan proyeksi proyeksi $\operatorname{proj}_{\mathbf{b}} \, \mathbf{a}$ dari a untuk menemukan proyeksi a pada $b^\perp$ sebagai:
$$\text{proj}_{A b} \, a = a - \text{proj}_b \, a$$
di mana:
$$\text{proj}_b \, a = \frac{a \cdot b}{||b||^2} b \quad \text{(1.1.10)}$$
di mana $b^\perp$ adalah vektor yang besarnya $||b||$ dan arahnya tegak lurus terhadap b

#### 1.1.2.4 Point-Plane Distance

Untuk menemukan rumus jarak dari titik p1 ke bidang, ambil titik sembarang $p₀ = [X₀, Y₀, Z₀]^T$ pada bidang dan vektor normal:
$$ n = [a, b, c,]^T \quad \text{(1.1.11)}$$
Mengapa $n$ merupakan vektor normal terhadap bidang? Karena tegak lurus terhadap bidang, atau secara ekuivalen, untuk vektor apa pun $p₀-p = [X₀-x, Y₀-y, Z₀-z]^T$ pada bidang di mana koordinat x, y, dan z dari $p₀$ dan $p = [x, y, z]$

![Figure 1.4 Distance from a point to a plane](Screenshot%202025-07-07%20111948.png)

Bagian-Bagian dalam Gambar:
* Bidang (Plane) Berwarna Pelangi
* Bidang ini adalah permukaan tempat kita ingin mengukur jarak dari sebuah titik di luar bidang.
* Didefinisikan oleh sebuah titik di bidang (p₀) dan vektor normal (n).

Titik-titik yang Ditunjukkan:
* p₀: Titik pada bidang (dapat digunakan sebagai referensi untuk menentukan bidang).
* p: Titik sembarang yang ingin diukur jaraknya ke bidang.
* p₁: Proyeksi dari titik p ke bidang (ini adalah titik terdekat pada bidang dari p).

Vektor-vektor:
* n (biru): Normal vector ke bidang. Vektor ini tegak lurus terhadap permukaan bidang.
* uₙ (biru gelap): Unit normal vector, yaitu n yang telah dinormalisasi (panjangnya = 1).
* p - p₀ (hitam): Vektor yang menghubungkan titik pada bidang p₀ ke titik p di luar bidang.

Proyeksi dan Jarak:
* Garis merah dari p ke p₁ adalah jarak tegak lurus (perpendicular distance) dari titik p ke bidang.
* Titik p₁ adalah proyeksi orthogonal dari p ke bidang.

Sistem Koordinat 3D (Kanan Bawah):
* Menunjukkan arah sumbu x, y, z dengan vektor basis uₓ, uᵧ, u𝓏.

### 1.1.3 CROSS PRODUCT

![Figure 1.6 Direction of cross product](Screenshot%202025-07-07%20113849.png)







Cross product antara dua vektor a dan b yang masing-masing ditulis dalam bentuk komponen kartesian $(a = a_xu_x + a_yu_y + a_zu_z, b = b_xu_x + b_yu_y + b_zu_z)$ menghasilkan vektor baru yang memiliki arah tegak lurus terhadap kedua vektor tersebut.

Besaran dan arah vektor hasil cross product dapat dihitung menggunakan rumus berikut:
$$\mathbf{a} \times \mathbf{b} = (a_y b_z - a_z b_y) \mathbf{u_x} + (a_z b_x - a_x b_z) \mathbf{u_y} + (a_x b_y - a_y b_x) \mathbf{u_z}$$
$$\begin{vmatrix}
\mathbf{u_x} & \mathbf{u_y} & \mathbf{u_z} \\
\mathbf{a_x} & \mathbf{a_y} & \mathbf{a_z} \\
\mathbf{b_x} & \mathbf{b_y} & \mathbf{b_z}
\end{vmatrix}
\quad=\begin{vmatrix}
a_y b_z - a_z b_y \\
a_z b_x - a_x b_z \\
a_x b_y - a_y b_x
\end{vmatrix} \quad \text{(1.1.12)}$$

Cross product bisa dihitung menggunakan determinan matriks:
$$\mathbf{a} \times \mathbf{b} = 
\begin{vmatrix}
\mathbf{u_x} & \mathbf{u_y} & \mathbf{u_z} \\
a_x & a_y & a_z \\
b_x & b_y & b_z \\
\end{vmatrix}$$


Tambahan:
* Arah a×b diberikan oleh aturan tangan kanan dalam arti bahwa ibu jari menunjuk ke arah a×b jika telunjuk (jari telunjuk) dan jari tengah menunjuk ke arah a dan b.




---
Contoh:

Dua vektor dalam sistem koordinat 3D:
$$𝑎=(2,3,4)$$
$$𝑏=(5,6,7)$$
Hitunglah a × b.

Penyelesaian:
* Tulis dalam bentuk determinan
$$\mathbf{a} \times \mathbf{b} = 
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
2 & 3 & 4 \\
5 & 6 & 7 \\
\end{vmatrix}$$
* Hitung determinannya
$$\mathbf{a} \times \mathbf{b} = 
\mathbf{i} 
\begin{vmatrix}
3 & 4 \\
6 & 7
\end{vmatrix}
- 
\mathbf{j} 
\begin{vmatrix}
2 & 4 \\
5 & 7
\end{vmatrix}
+ 
\mathbf{k} 
\begin{vmatrix}
2 & 3 \\
5 & 6
\end{vmatrix}$$
* Hitung masing-masing determinan minor
Untuk i: $$(3)(7)−(4)(6)=21−24=−3$$
Untuk j: $$(2)(7)−(4)(5)=14−20=−6$$
Untuk k: $$(2)(6)−(3)(5)=12−15=−3$$
* Gabungkan hasilnya
$$a×b=(−3)i−(−6)j+(−3)k$$
$$a×b=(−3,6,−3)$$

#### 1.1.3.1 Triple Scalar Product and Triple Vector Product

Produk silang adalah operasi matematis yang menghasilkan vektor baru yang tegak lurus terhadap dua vektor yang dikalikan, dalam ruang tiga dimensi.

Kita bisa membuktikan kesetaraan di antara:
* Tiga produk skalar rangkap tiga:
$$ (a \times b) \cdot c = (b \times c) \cdot a = (c \times a) \cdot b \quad \text{(1.1.13)}$$
* Tiga produk vektor rangkap tiga
$$ a \times (b \times c)=(c \cdot a)b-(b \cdot a )c \quad \text {(1.1.14)}$$

Beberapa sifat dari produk silang yaitu:
* Produk silang bersifat tidak komutatif, artinya $\mathbf{a} \times \mathbf{b}$ tidak sama dengan $\mathbf{b} \times \mathbf{a}$, justru hasilnya berlawanan arah.
* Produk silang bersifat distributif terhadap penjumlahan, artinya $ \mathbf{a} \times (\mathbf{b} + \mathbf{c}) = \mathbf{a} \times \mathbf{b} + \mathbf{a} \times \mathbf{c}$ 
* Hasil produk silang dari dua vektor yang sejajar (kolinear) adalah vektor nol, yaitu $\mathbf{a} \times \mathbf{b} = 0$ jika 𝑎 dan 𝑏 sejajar.

#### 1.1.3.2 Jacobi Identity

Produk silang dari dua vektor menghasilkan sebuah vektor yang tegak lurus terhadap kedua vektor tersebut. Dalam hal ini, identitas Jacobi berhubungan dengan bagaimana kita dapat menyusun ulang urutan operasi produk silang di dalam sebuah ekspresi yang melibatkan tiga vektor.

Secara matematis, identitas ini diekspresikan dalam bentuk persamaan berikut:
$$ a \times (b \times c)=(a \times b) \times c-(a \times c)\times b$$

Menggunakan rumus 1.1.14 kita dapat membuktikan identitas jacobi:
$$ a \times(b\times c)+b \times(c \times a)+c \times (a \times b)=0 \quad \text{(1.1.15a)}$$
$$ (a \times b)\times c+(b \times c)\times a+(c \times a)\times b=0 \quad \text{(1.1.15b)}$$

### 1.1.4 LINES AND PLANES

#### 1.1.4.1 Vector Equation of a Line

![Figure 1.8 Vector equation of a line with direction vector d](Screenshot%202025-07-07%20115838.png)  

Persamaan vektor untuk garis dengan vektor arah d yang melewati titik p1 adalah:
$$\mathbf{p} = \mathbf{p}_1 + \mathbf{d}t \quad\text{(1.1.16)}$$ 

Dengan demikian, persamaan vektor untuk garis yang melalui dua titik yang berbeda p1 dan p2 adalah:
$$p = p_1 + t(p_2 - p_1)$$ 
dengan vektor arah 
$$d=p_2-p_1 \quad \text{(1.1.17)}$$

### 1.1.4.2 Vector Equation of a Plane

![Figure 1.9 Vector equation of a plane](./Screenshot%202025-07-07%20120807.png)  

Sebuah bidang (plane) dalam ruang tiga dimensi bisa dinyatakan dengan persamaan vektor jika diketahui sebuah vektor normal dan satu titik pada bidang tersebut.
 Misalkan:
 * Titik $p1=[x_1,y_1,z_1]^T$ adalah titik pada bidang
 * Vektor normal bidang tersebut adalah $n=[a,b,c]^T$
Maka, persamaan vektor bidang adalah:
$$ n \cdot (p-p_1)=0 \quad \text{(1.1.18)}$$
Ini menyatakan bahwa vektor dari 𝑝1 ke titik mana pun 𝑝 di bidang tersebut tegak lurus (ortogonal) terhadap vektor normal 𝑛.

Dalam bentuk Kartesius, persamaan bidang tersebut menjadi:
$$ a(x-x_1)+b(y-y_1)+c(z-z_1)=0 \quad \text{(1.1.19)}$$

Example 1.1 Finding a Normal Vector to a Plane

In [ ]:
import numpy as np

p1 = np.array([0, 0, 2/9])
p2 = np.array([1, 0, 1/3])
p3 = np.array([0, 1, 1/9])

v1 = p2 - p1
v2 = p3 - p1

normal_vector = np.cross(v1, v2)

unit_normal = normal_vector / np.linalg.norm(normal_vector)

print("Vektor Normal (tidak dinormalisasi):", normal_vector)
print("Vektor Normal (satuannya):", unit_normal)


Vektor Normal (tidak dinormalisasi): [-0.11111111  0.11111111  1.        ]
Vektor Normal (satuannya): [-0.10976426  0.10976426  0.98787834]


### 1.1.4.3 Intersection of Two Planes

Untuk mencari persamaan vektor garis perpotongan dua bidang (misalnya bidang 𝑃𝑎 dan 𝑃𝑏), terdapat dua langkah utama:
* Menentukan satu titik 𝑝1 yang merupakan titik potong dari kedua bidang.
* Menentukan vektor arah 𝑑 dari garis potong, yang didapat dari hasil perkalian silang (cross product) dari dua vektor normal 𝑛𝑎 dan 𝑛𝑏 dari masing-masing bidang.

Setelah dua komponen di atas ditemukan, maka persamaan vektor garis potong ditulis menggunakan rumus:
$$ p(t)=p_1+t(n_a \times n_b) \quad \text{(1.1.20)}$$

Example 1.2 Finding the Line of Intersection of Two Planes

In [4]:
import numpy as np

# Definisikan koefisien bidang dalam bentuk Ax + By + Cz = D
# Bidang 1: 2x - 3y + 4z = 1
# Bidang 2:  x -  y -  z = 5

# Matriks normal (A)
A = np.array([[2, -3, 4],
              [1, -1, -1]])

# Vektor konstanta (dikalikan -1 agar jadi Ax + By + Cz - D = 0)
b = np.array([1, 5])

# Cari vektor arah dari garis potong → cross product dari dua vektor normal
n1 = np.array([2, -3, 4])
n2 = np.array([1, -1, -1])
direction = np.cross(n1, n2)  # vektor arah d

# Temukan satu titik pada garis perpotongan
# Misal, tetapkan z = 0, selesaikan sistem dua persamaan linier
C = np.array([[2, -3],
              [1, -1]])
d_vec = np.array([1, 5])
xy = np.linalg.solve(C, d_vec)
p1 = np.array([xy[0], xy[1], 0])  # Titik potong

# Cetak hasil
print("Titik potong (p1):", p1)
print("Vektor arah (d):", direction)

# Bentuk persamaan garis parametris
t = np.linspace(-2, 2, 5)  # beberapa nilai parameter t
points = p1.reshape(3, 1) + direction.reshape(3, 1) * t

print("\nBeberapa titik pada garis:")
print(points.T)


Titik potong (p1): [14.  9.  0.]
Vektor arah (d): [7 6 1]

Beberapa titik pada garis:
[[ 0. -3. -2.]
 [ 7.  3. -1.]
 [14.  9.  0.]
 [21. 15.  1.]
 [28. 21.  2.]]


![Figure 1.10 Line of intersection between two planes](./Screenshot%202025-07-07%20121214.png)  

Gambar ini menunjukkan dua bidang datar (plane) di ruang tiga dimensi yang saling berpotongan, dan membentuk sebuah garis perpotongan (line of intersection).
* Plane 1 (warna ungu-pink) adalah bidang pertama, dengan normal vector n₁ (vektor normal tegak lurus terhadap bidang).
* Plane 2 (warna biru-hijau) adalah bidang kedua, dengan normal vector n₂.
Normal vector (ditunjukkan dengan panah) adalah vektor yang tegak lurus terhadap permukaan bidang. Setiap bidang memiliki satu vektor normal khas.
* Ketika dua bidang berpotongan, hasilnya adalah sebuah garis lurus.
* Arah garis perpotongan adalah hasil dari perkalian silang (cross product) dua vektor normal:
$$ d=n₁ × n₂$$
Ini karena garis perpotongan harus tegak lurus terhadap kedua vektor normal.


### 1.1.4.4 Intersection of a Plane and a Line

![Figure 1.11 Intersection of a plane and a line](./Screenshot%202025-07-07%20121830.png)  

Gambar ini menunjukkan perpotongan antara sebuah bidang (plane) dan sebuah garis (line) di dalam ruang tiga dimensi (3D).
* Bidang (Plane): Ditampilkan sebagai permukaan berwarna pelangi yang membentang di ruang 3D.
* Garis (Line): Ditunjukkan dengan garis berwarna biru yang menembus bidang.
* Vektor Normal (n): Vektor berwarna hijau yang tegak lurus terhadap bidang.
* p₁: Titik yang terletak di atas bidang (bisa dianggap sebagai titik acuan di bidang).
* p₂: Titik pada garis.
* p: Titik perpotongan antara garis dan bidang (intersection point).
Titik perpotongan ini adalah solusi simultan antara persamaan garis dan persamaan bidang.
---
Bidang dapat dinyatakan dengan persamaan vektor:
$$ n \cdot (p-p1) = 0 \quad \text{(1.1.42)}$$
atau dalam bentuk skalar: 
$$n_x (x - x_1) + n_y (y - y_1) + n_z (z - z_1) = 0$$
* n = (n_x, n_y, n_z) = Vektor normal bidang.
* p₁ = (x_1, y_1, z_1) = Titik yang ada di bidang.
* p: Titik sembarang yang terletak di bidang.

Garis dapat dinyatakan dengan persamaan vektor:
$$p= p2 + td \quad \text{(1.1.43)}$$
atau secara skalar:
$$x = x_2 + d_xt$$
$$y = y_2 + d_yt$$
$$z = z_2 + d_zt$$
* p: Posisi sembarang titik pada garis.
* p₂ = (x_2, y_2, z_2) = Titik awal (point on the line).
* d = (d_x, d_y, d_z) = Vektor arah garis.
* t: Parameter skalar yang menentukan posisi di sepanjang garis.

Langkah Menentukan Titik Perpotongan:
1. Substitusi persamaan garis ke persamaan bidang:
$$ n_x(x_2+d_xt-x_1)+n_y(y_2+d_yt-y_1)+n_z(z_2+d_zt-z_1)=0$$
2. Sederhanakan:
$$n_x (x_2 - x_1) + n_y (y_2 - y_1) + n_z (z_2 - z_1) + t (n_x d_x + n_y d_y + n_z d_z) = 0$$
3. Pecahkan untuk t:
$$t = -\frac{n_x (x_2 - x_1) + n_y (y_2 - y_1) + n_z (z_2 - z_1)}{n_x d_x + n_y d_y + n_z d_z}$$
Penyebut adalah dot product antara vektor normal bidang dan vektor arah garis.

4. Temukan Titik Potong:

Setelah nilai t diperoleh, masukkan kembali ke persamaan garis:
$$x = x_2 + d_xt$$
$$y = y_2 + d_yt$$
$$z = z_2 + d_zt$$
Inilah koordinat titik potongnya.






Example 1.3 Finding the Intersection of a Plane and a Line

In [7]:
import numpy as np

# Normal vector of the plane
n = np.array([1, 1, 5])

# A point on the plane
p1 = np.array([2, -1, 0])

# A point on the line
p2 = np.array([1, 0, 2])

# Direction vector of the line
d = np.array([-1, 1, -2])

# Calculate parameter t using dot product
numerator = np.dot(n, p1 - p2)
denominator = np.dot(n, d)

if denominator == 0:
    if numerator == 0:
        print("Garis terletak di bidang (tak hingga titik potong).")
    else:
        print("Garis sejajar bidang dan tidak memotong.")
else:
    t = numerator / denominator
    intersection_point = p2 + t * d
    print("Titik potong:", intersection_point)


Titik potong: [0. 1. 0.]


#### 1.1.6 COORDINATE SYSTEMS

1. Sistem koordinat Kartesius (rectangular) adalah sistem yang digunakan untuk menentukan posisi titik dalam ruang 2D atau 3D menggunakan bilangan real sebagai koordinatnya.
* Dalam 2D, posisi ditentukan oleh pasangan (𝑥,𝑦)
* Dalam 3D, posisi ditentukan oleh tripel (𝑥,𝑦,𝑧)

![Figure 1.14.1 Cartesian coordinate system](Screenshot%202025-07-07%20130653.png)

2. Sistem koordinat silinder adalah sistem koordinat yang digunakan untuk mendeskripsikan posisi suatu titik dalam ruang tiga dimensi berdasarkan:
* Jarak radial dari sumbu-z ke proyeksi titik di bidang-xy (𝑟)
* Sudut terhadap sumbu-x di bidang-xy (dengan arah berlawanan jarum jam) (𝜑)
* Tinggi vertikal bidang xy (sama dengan Kartesius) (𝑧)

![Figure 1.14.2 Cylindrical coordinate system](Screenshot%202025-07-07%20131455.png)

3. Sistem koordinat bola (spherical coordinate system) adalah sistem koordinat yang digunakan untuk menentukan posisi suatu titik dalam ruang 3D dengan: 
* Radius (r): Jarak dari titik ke pusat (asal koordinat).
* Sudut polar (θ): Sudut antara vektor posisi dengan sumbu-z (juga dikenal sebagai elevation angle atau colatitude).
* Sudut azimut (ϕ): Sudut rotasi proyeksi titik di bidang xy terhadap sumbu-x (sama seperti dalam sistem silinder).

![Figure 1.14.3 Spherical coordinate system](Screenshot%202025-07-07%20133021.png)